/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;


namespace MyService
{
  public static class sampleConstants
  {
    public const int MAX_PASSWORD_LEN = 13;
    public const string DEFAULT_API_SERVER_URL = "https://server.url.com/api/v1/\nabc";
  }
}
