/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace MyService
{
  public enum ServicePlatformType
  {
    Google = 0,
    Apple = 1,
    Facebook = 2,
    Twitter = 3,
    OneStore = 4,
  }
}
