--
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
-- @generated
--

require 'Thrift'

MAX_PASSWORD_LEN = 13

DEFAULT_API_SERVER_URL = 'https://server.url.com/api/v1/abc'
