/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sample_constants.h"

namespace MyService {

const sampleConstants g_sample_constants;

sampleConstants::sampleConstants() {
  MAX_PASSWORD_LEN = 13;

  DEFAULT_API_SERVER_URL = "https://server.url.com/api/v1/\nabc";

}

} // namespace

