/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sample_CONSTANTS_H
#define sample_CONSTANTS_H

#include "sample_types.h"

namespace MyService {

class sampleConstants {
 public:
  sampleConstants();

  int32_t MAX_PASSWORD_LEN;
  std::string DEFAULT_API_SERVER_URL;
};

extern const sampleConstants g_sample_constants;

} // namespace

#endif
