<?php
namespace MyService;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface AuthIf
{
    /**
     * API 서버에게 로그인을 요청합니다.
     * 
     * @param \MyService\LoginRequest $request
     * @return \MyService\LoginResponse
     */
    public function Login(\MyService\LoginRequest $request);
    /**
     * API 서버에게 로그아웃을 요청합니다.
     * 
     * @param \MyService\LogoutRequest $request
     * @return \MyService\LogoutResponse
     */
    public function Logout(\MyService\LogoutRequest $request);
}
