<?php
namespace MyService;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class Constant extends \Thrift\Type\TConstant
{
    static protected $MAX_PASSWORD_LEN;
    static protected $DEFAULT_API_SERVER_URL;

    protected static function init_MAX_PASSWORD_LEN()
    {
        return 13;
    }

    protected static function init_DEFAULT_API_SERVER_URL()
    {
        return "https://server.url.com/api/v1/\nabc";
    }
}
