<?php
namespace MyService;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class LoginResponse
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'session_key',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'newbee',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
    );

    /**
     * 세션키
     * 
     * @var string
     */
    public $session_key = "1234";
    /**
     * 신규 가입자인지 여부
     * 
     * @var bool
     */
    public $newbee = false;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['session_key'])) {
                $this->session_key = $vals['session_key'];
            }
            if (isset($vals['newbee'])) {
                $this->newbee = $vals['newbee'];
            }
        }
    }

    public function getName()
    {
        return 'LoginResponse';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->session_key);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->newbee);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('LoginResponse');
        if ($this->session_key !== null) {
            $xfer += $output->writeFieldBegin('session_key', TType::STRING, 1);
            $xfer += $output->writeString($this->session_key);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->newbee !== null) {
            $xfer += $output->writeFieldBegin('newbee', TType::BOOL, 2);
            $xfer += $output->writeBool($this->newbee);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
