<?php
namespace MyService;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class ServicePlatformType
{
    /**
     * 구글
     */
    const Google = 0;

    /**
     * 애플
     */
    const Apple = 1;

    /**
     * 페이스북
     */
    const Facebook = 2;

    /**
     * Twitter
     */
    const Twitter = 3;

    /**
     * 원스토어
     */
    const OneStore = 4;

    static public $__names = array(
        0 => 'Google',
        1 => 'Apple',
        2 => 'Facebook',
        3 => 'Twitter',
        4 => 'OneStore',
    );
}

