//
// Autogenerated by Thrift Compiler (0.13.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Int64 = require('node-int64');

import { sample } from "./sample_types";

declare module "./sample_types" {
  module sample {

    class AuthClient {
      input: Thrift.TJSONProtocol;
      output: Thrift.TJSONProtocol;
      seqid: number;

      constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

      /**
       * API 서버에게 로그인을 요청합니다.
       */
      Login(request: MyService.LoginRequest): MyService.LoginResponse;

      /**
       * API 서버에게 로그인을 요청합니다.
       */
      Login(request: MyService.LoginRequest, callback?: (data: MyService.LoginResponse) => void): void;

      /**
       * API 서버에게 로그아웃을 요청합니다.
       */
      Logout(request: MyService.LogoutRequest): MyService.LogoutResponse;

      /**
       * API 서버에게 로그아웃을 요청합니다.
       */
      Logout(request: MyService.LogoutRequest, callback?: (data: MyService.LogoutResponse) => void): void;
    }
  }
}
