/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace MyService
{
  public enum ServicePlatformType
  {
    /// <summary>
    /// 구글
    /// </summary>
    Google = 0,
    /// <summary>
    /// 애플
    /// </summary>
    Apple = 1,
    /// <summary>
    /// 페이스북
    /// </summary>
    Facebook = 2,
    /// <summary>
    /// Twitter
    /// </summary>
    Twitter = 3,
    /// <summary>
    /// 원스토어
    /// </summary>
    OneStore = 4,
  }
}
